apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: front-cheve
  description: The place to be
  labels:
    system: public-websites
  annotations:
    example.com/service-discovery: frontcheve
    circleci.com/project-slug: github/example-org/front-cheve
  tags:
    - node
spec:
  type: website
  lifecycle: production
  owner: front-cheve-team
